# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

greg_cpp_one <- function(W, C, B) {
    .Call(`_taxsimutilities_greg_cpp_one`, W, C, B)
}

fast_bs_sum <- function(pattern) {
    .Call(`_taxsimutilities_fast_bs_sum`, pattern)
}

fast_group_sum <- function(x, grp) {
    .Call(`_taxsimutilities_fast_group_sum`, x, grp)
}

fast_group_max <- function(x, grp) {
    .Call(`_taxsimutilities_fast_group_max`, x, grp)
}

fast_group_min <- function(x, grp) {
    .Call(`_taxsimutilities_fast_group_min`, x, grp)
}

gini_sorted <- function(y, w) {
    .Call(`_taxsimutilities_gini_sorted`, y, w)
}

fast_poverty <- function(y, w, k, ncores) {
    .Call(`_taxsimutilities_fast_poverty`, y, w, k, ncores)
}

fast_med <- function(y, w) {
    .Call(`_taxsimutilities_fast_med`, y, w)
}

fast_pov <- function(y, w, thres) {
    .Call(`_taxsimutilities_fast_pov`, y, w, thres)
}

fast_cpov <- function(y, w, k, thres) {
    .Call(`_taxsimutilities_fast_cpov`, y, w, k, thres)
}

fast_povgap <- function(y, w, thres, exp) {
    .Call(`_taxsimutilities_fast_povgap`, y, w, thres, exp)
}

theil_l <- function(y, w) {
    .Call(`_taxsimutilities_theil_l`, y, w)
}

theil_t <- function(y, w) {
    .Call(`_taxsimutilities_theil_t`, y, w)
}

gen_ent <- function(y, w, a) {
    .Call(`_taxsimutilities_gen_ent`, y, w, a)
}

atkinson_1 <- function(y, w) {
    .Call(`_taxsimutilities_atkinson_1`, y, w)
}

atkinson_e <- function(y, w, e) {
    .Call(`_taxsimutilities_atkinson_e`, y, w, e)
}

greg_cpp <- function(W, C, B, L, U) {
    .Call(`_taxsimutilities_greg_cpp`, W, C, B, L, U)
}

run_sim_cpp_parallel <- function(iters, M, N, in_matrix, U, V, ID, out_matrix, cw, lambda, ncores, seed) {
    invisible(.Call(`_taxsimutilities_run_sim_cpp_parallel`, iters, M, N, in_matrix, U, V, ID, out_matrix, cw, lambda, ncores, seed))
}

