# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
greg_cpp_one <- function(W, C, B) {
    .Call(`_taxsimutilities_greg_cpp_one`, W, C, B)
}

#' @export
fast_bs_sum <- function(pattern) {
    .Call(`_taxsimutilities_fast_bs_sum`, pattern)
}

#' @useDynLib taxsimutilities, .registration = TRUE
#' @importFrom Rcpp evalCpp
NULL

#' @export
logSumExp <- function(logV, accumulators = 8L) {
    .Call(`_taxsimutilities_logSumExp`, logV, accumulators)
}

#' @export
stable_ig <- function(U, W, N, M) {
    .Call(`_taxsimutilities_stable_ig`, U, W, N, M)
}

#' @export
stable_n <- function(U, W, N, M) {
    .Call(`_taxsimutilities_stable_n`, U, W, N, M)
}

#' @export
stable_p <- function(U, W, N, M) {
    .Call(`_taxsimutilities_stable_p`, U, W, N, M)
}

#' @export
llc_cpp <- function(p, H1, H2, H1sq, H2sq, H1H2, Y, H1Y, H2Y, Ysq, TW, nw, N, M) {
    .Call(`_taxsimutilities_llc_cpp`, p, H1, H2, H1sq, H2sq, H1H2, Y, H1Y, H2Y, Ysq, TW, nw, N, M)
}

#' @export
llc_alt_cpp <- function(p, H1, H2, H1sq, H2sq, H1H2, Y, H1Y, H2Y, Ysq, lTW, nw, N, M) {
    .Call(`_taxsimutilities_llc_alt_cpp`, p, H1, H2, H1sq, H2sq, H1H2, Y, H1Y, H2Y, Ysq, lTW, nw, N, M)
}

#' @export
lls_cpp <- function(p, H, Hsq, Y, Ysq, HY, TW, nw, N, M) {
    .Call(`_taxsimutilities_lls_cpp`, p, H, Hsq, Y, Ysq, HY, TW, nw, N, M)
}

#' @export
lls_alt_cpp <- function(p, H, Hsq, Y, Ysq, HY, lTW, nw, N, M) {
    .Call(`_taxsimutilities_lls_alt_cpp`, p, H, Hsq, Y, Ysq, HY, lTW, nw, N, M)
}

#' @export
llsopt_cpp <- function(p, H, Hsq, Y, Ysq, HY, TW, nw, N, M, opt_mode) {
    .Call(`_taxsimutilities_llsopt_cpp`, p, H, Hsq, Y, Ysq, HY, TW, nw, N, M, opt_mode)
}

#' @export
fast_group_sum <- function(x, grp) {
    .Call(`_taxsimutilities_fast_group_sum`, x, grp)
}

#' @export
fast_group_max <- function(x, grp) {
    .Call(`_taxsimutilities_fast_group_max`, x, grp)
}

#' @export
fast_group_min <- function(x, grp) {
    .Call(`_taxsimutilities_fast_group_min`, x, grp)
}

#' @export
gini_sorted <- function(y, w) {
    .Call(`_taxsimutilities_gini_sorted`, y, w)
}

#' @export
fast_poverty <- function(y, w, k, ncores) {
    .Call(`_taxsimutilities_fast_poverty`, y, w, k, ncores)
}

#' @export
fast_med <- function(y, w) {
    .Call(`_taxsimutilities_fast_med`, y, w)
}

#' @export
fast_pov <- function(y, w, thres) {
    .Call(`_taxsimutilities_fast_pov`, y, w, thres)
}

#' @export
fast_cpov <- function(y, w, k, thres) {
    .Call(`_taxsimutilities_fast_cpov`, y, w, k, thres)
}

#' @export
fast_povgap <- function(y, w, thres, exp) {
    .Call(`_taxsimutilities_fast_povgap`, y, w, thres, exp)
}

#' @export
theil_l <- function(y, w) {
    .Call(`_taxsimutilities_theil_l`, y, w)
}

#' @export
theil_t <- function(y, w) {
    .Call(`_taxsimutilities_theil_t`, y, w)
}

#' @export
gen_ent <- function(y, w, a) {
    .Call(`_taxsimutilities_gen_ent`, y, w, a)
}

#' @export
atkinson_1 <- function(y, w) {
    .Call(`_taxsimutilities_atkinson_1`, y, w)
}

#' @export
atkinson_e <- function(y, w, e) {
    .Call(`_taxsimutilities_atkinson_e`, y, w, e)
}

#' @export
greg_cpp <- function(W, C, B, L, U) {
    .Call(`_taxsimutilities_greg_cpp`, W, C, B, L, U)
}

#' @export
run_sim_cpp_parallel <- function(iters, M, N, in_matrix, U, V, ID, out_matrix, cw, lambda, ncores, seed) {
    invisible(.Call(`_taxsimutilities_run_sim_cpp_parallel`, iters, M, N, in_matrix, U, V, ID, out_matrix, cw, lambda, ncores, seed))
}

#' @export
test_int <- function(x, y) {
    .Call(`_taxsimutilities_test_int`, x, y)
}

#' @export
test_intm <- function(x, y, integral, M, N, ncores) {
    invisible(.Call(`_taxsimutilities_test_intm`, x, y, integral, M, N, ncores))
}

#' @export
stable_point <- function(U, w) {
    .Call(`_taxsimutilities_stable_point`, U, w)
}

#' @export
stable_pointv <- function(U, w) {
    .Call(`_taxsimutilities_stable_pointv`, U, w)
}

#' @export
int_optv <- function(re, row, hrs, disp, tw, mn, sdv) {
    .Call(`_taxsimutilities_int_optv`, re, row, hrs, disp, tw, mn, sdv)
}

#' @export
int_optrc <- function(re, hrs1, hrs2, disp, tw, mn) {
    .Call(`_taxsimutilities_int_optrc`, re, hrs1, hrs2, disp, tw, mn)
}

#' @export
int_optr <- function(re, hrs, disp, tw, mn) {
    .Call(`_taxsimutilities_int_optr`, re, hrs, disp, tw, mn)
}

#' @export
recalc_quants <- function(optp, hrs, disp, tw, mn, N, M) {
    invisible(.Call(`_taxsimutilities_recalc_quants`, optp, hrs, disp, tw, mn, N, M))
}

#' @export
int_optvc <- function(re, row, h1, hrs1, h2, hrs2, y1, disp, tw, mn, std) {
    .Call(`_taxsimutilities_int_optvc`, re, row, h1, hrs1, h2, hrs2, y1, disp, tw, mn, std)
}

